services:
  - type: web
    name: chatroom-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://awsproject:awsproject@awsproject.fvreojm.mongodb.net/?appName=awsproject
      - key: JDOODLE_CLIENT_ID
        sync: false
      - key: JDOODLE_CLIENT_SECRET
        sync: false 